language: python

services:
  - docker

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true


# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install codecov

install:
  - pip install .

# command to run tests
script:
  - pytest
  - codecov
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      cd ./docs;
      make html;
      make html;
      make html;
      touch _build/html/.nojekyll;
    fi
    
before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
      condition: "$TRAVIS_PYTHON_VERSION = 3.7"
    local_dir: docs/_build/html
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      tags: true
    distributions: "sdist bdist_wheel"
    skip_existing: true
